### ISSUE TITLE
QLauncher cannot get Node ID

### ISSUE THREAD

**Issue by jjchangg** [poseidon-network/qlauncher-linux#1]
When I run "./qlauncher.sh start", it shows 

![log](https://user-images.githubusercontent.com/65033954/81429793-eb773e00-9190-11ea-934a-0da9a783c48b.JPG)

what can i do? thanks in advance.

**Comment by morchory** [comment]
try 

apt-get install curl wget net-tools

**Comment by jjchangg** [comment]
it's ok now. the root caused is firewall & routing setting issues.

> try
> 
> apt-get install curl wget net-tools

**Comment by jjchangg** [comment]
it's ok now. the root caused is firewall & routing setting issues.

**Comment by jjchangg** [comment]
it's ok now.
