### ISSUE TITLE
really good update👍

### ISSUE THREAD

**Issue by yudiwdynto** [poseidon-network/qlauncher-linux#11]
but, why good? because I no longer get points after the latest version came, yes latest version 0.2.4.5.

hey hey wait, are you sure? ofc 💯 
after getting an OTA update, my ipfs services not working
![IMG_20200704_003043](https://user-images.githubusercontent.com/25768748/86489150-9d944600-bd8d-11ea-93f4-668a80639a72.jpg)
dude, try restarting and still with the same status

and after I tried to downgrade it only ended in disaster
![IMG_20200704_003223](https://user-images.githubusercontent.com/25768748/86489208-d8967980-bd8d-11ea-877e-878232d54c8f.jpg)

ah,, damn what should I do now, crying? it didn't solve my problem.
AND
what's next? v2ray? nginx?

**Comment by jakues** [comment]
wth, 😫

**Comment by KevinChen0718** [comment]
@yudiwdynto Hi, can you pm me? I want to get some information with you
