### ISSUE TITLE
How to run qlauncher on start up ?

### ISSUE THREAD

**Issue by pixyruri** [poseidon-network/qlauncher-linux#2]
help

**Comment by coderkk** [comment]
Can you try the steps below:

1. create config file with root privilege at /etc/systemd/system/qlauncher.service with content below: (please replace /root/qlauncher with actual installation path)
[Unit]
Description=qlauncher.service
[Service]
Type=simple
ExecStart=/root/qlauncher/qlauncher.sh start
ExecStop=/root/qlauncher/qlauncher.sh stop
[Install]
WantedBy=multi-user.target
2. sudo systemctl daemon-reload
3. sudo systemctl enable qlauncher
4. sudo systemctl start qlauncher

**Comment by coderkk** [comment]
@pixyruri May I know it is working? Thank you.
