### ISSUE TITLE
FATA[2021-06-23T12:58:35.685417531Z] load config file: stat /

### ISSUE THREAD

**Issue by djingwu** [poseidon-network/qlauncher-linux#20]
/opt/qlauncherV2/qlauncher.sh status
INFO[0000] Acquiring lock file /var/lib/rancher/k3s/data/.lock 
INFO[0000] Preparing data dir /var/lib/rancher/k3s/data/b9574be94e4edbdbb93a39a2cb1f4e4df3ba699171a8b86863d1e8c421c91f63 
FATA[2021-06-23T12:58:35.685417531Z] load config file: stat /var/lib/rancher/k3s/data/b9574be94e4edbdbb93a39a2cb1f4e4df3ba699171a8b86863d1e8c421c91f63/bin/crictl.yaml: no such file or directory

**Comment by coderkk** [comment]
Can you try `sudo /opt/qlauncherV2/qlauncher.sh status`?

**Comment by jjchangg** [comment]
> Can you try `sudo /opt/qlauncherV2/qlauncher.sh status`?

i have the same issue. Try `sudo /opt/qlauncherV2/qlauncher.sh status` was the same.

**Comment by coderkk** [comment]
Can you try `sudo -i` 1st. Then, `/opt/qlauncherV2/qlauncher.sh status`.

**Comment by jjchangg** [comment]
Hi,

I've reinstalled, no those issues again. But I think you(internal) are
adjusted the service, it caused those issues.

JJ

coderkk ***@***.***> 於 2021年6月28日 週一 下午5:50寫道：

**Comment by coderkk** [comment]
@jjchangg Noted

@djingwu Do you still face the issue?

**Comment by djingwu** [comment]
No problem，the repeated machine cause

**Comment by Hugo6991** [comment]
Thank you for your report, @djingwu. I'd like to thank @YH for helping resolve this issue 🙇🏻‍♂️
