### ISSUE TITLE
unable to load container

### ISSUE THREAD

**Issue by ShibaTeo** [poseidon-network/qlauncher-linux#21]
![image](https://user-images.githubusercontent.com/86594150/123601218-fe801e00-d829-11eb-99c0-268205051046.png)

unable to load container with FATA

pls help

**Comment by Pawelpwg** [comment]
Same problem on my two boxes, started 2h ago

**Comment by coderkk** [comment]
@Pawelpwg @ShibaTeo Can you try `sudo -i` 1st. Then, `/opt/qlauncherV2/qlauncher.sh status`.

**Comment by Pawelpwg** [comment]
Already tried that, also restasrting, stoping and starting using sudo

everything was running tottaly fine, and today blow up

**Comment by Pawelpwg** [comment]
![Uploading image.jpg…]()

**Comment by coderkk** [comment]
Maybe try reinstall?

**Comment by ShibaTeo** [comment]
> @Pawelpwg @ShibaTeo Can you try `sudo -i` 1st. Then, `/opt/qlauncherV2/qlauncher.sh status`.

yes it works
