### ISSUE TITLE
Storage space usage slow down after 6/28

### ISSUE THREAD

**Issue by jjchangg** [poseidon-network/qlauncher-linux#24]
I don't know if it's a problem. After Poseidon-network finished adjusting on 6/28, my storage space dropped to 0. Then I restarted it on 6/29, but the storage usage speed is several times slower than the other nodes or compared to itself in previous week.

**Comment by coderkk** [comment]
qlauncher will create a fix disk image, so it will not use the other folder. Maybe you need to check whether there have any temp files the OS recently generate.

**Comment by vickygao77** [comment]
We appreciate you taking the time to give us feedback. 😊

This is a 6/28 global system issue. We have solved this problem that day. This problem caused all stored data on all test nodes to be deleted. 
After we resolved this issue, it has not recurred so far.

We are continuing to work hard to make the decentralized network more stable and more powerful so we can gather all of you together. We appreciate all of your support. 🙌
