### ISSUE TITLE
tar -vxzf app.tar.gz -C ~/qlauncher/

### ISSUE THREAD

**Issue by super-marco** [poseidon-network/qlauncher-linux#3]
root@2:~# tar -vxzf app.tar.gz -C ~/qlauncher/
tar (child): app.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
執行最後一個指令時 會出現app.tar.gz沒有這個檔案的問題

**Comment by coderkk** [comment]
請試下 tar -vxzf ql-linux.tar.gz -C ~/qlauncher/

**Comment by coderkk** [comment]
我想你的指令有中文亂碼。試下 copy and paste 以下指令

`
tar -vxzf ql-linux.tar.gz -C ~/qlauncher/
`

**Comment by super-marco** [comment]
可以了 要改 tar -vxzf ql-linux.tar.gz -C ~/qlauncher/
