### ISSUE TITLE
[BUG] Can't run at startup

### ISSUE THREAD

**Issue by jakues** [poseidon-network/qlauncher-linux#31]
### Describe the bug**
Qlauncher can't run as startup by enabling `systemctl enable qlauncher` its show an error. 

### Basic contact
Discord username: rill#5885
QQQ APP UID: [e.g. 53564]
QLauncher ID: "f1c017f892293295a56e90d660ffe5ed"

!Notice : Please PM our community support if your QLauncher has not added your QQQ app account yet.

### Expected behavior
Hope on installer there can setup variable when submit path storage

### Screenshots
Take a screenshot of the following commands and provide it to us:
sudo tail /opt/qlauncherV2/log/agent.log
sudo tail /opt/qlauncherV2/log/qlauncher.log
![image](https://user-images.githubusercontent.com/34295920/127795977-9348cdf8-5589-4d96-970a-4c89343c631b.png)

### Smartphone (please complete the following information):**
 - QQQ APP Version [e.g. v 1.28 ]

**Comment by mika756** [comment]
in my vm try reboot vm and reinstall ql can't solve this problem

**Comment by coderkk** [comment]
We appreciate you taking the time to give us feedback. 😊

【 New mining devices unavailable to join testnet temporary 】

In order to figure out the problem, developers need to temporarily stop new devices from joining. The previous mining devices won’t be affected.

Our announcements will notify you when new mining devices are available to join the testnet once the issues are fixed. Thank you for your cooperation.

**Comment by mika756** [comment]
my device runing normaly in few days ago, then any member in discord ask about bug if vm reboot ql can't run again, and i test reboot my vm and true can't run ql after reboot

**Comment by coderkk** [comment]
@mika756 This issue also affect the current user. Our engineers are checking the issue.

**Comment by coderkk** [comment]
We have updated the services. Please try to restart your qlauncher. Thanks

**Comment by jakues** [comment]
> 
> 
> We have updated the services. Please try to restart your qlauncher. Thanks

it working thanks . I will close this issue, 
![image](https://user-images.githubusercontent.com/34295920/128125812-03b6bc92-4de1-4e72-afea-aad8f72cd934.png)

**Comment by jakues** [comment]
> 
> 
> We have updated the services. Please try to restart your qlauncher. Thanks

sar, can you make script installer possible setup variable when submit path storage ?

**Comment by jakues** [comment]
issue open again due to bug on startup

**Comment by jakues** [comment]
Bug Solved 
Thanks @coderkk @mika756
