### ISSUE TITLE
Service Stopping IPFS 0  + Port Configuration Assistance Please

### ISSUE THREAD

**Issue by 2020movievault** [poseidon-network/qlauncher-linux#32]
Two issues 
1) This issue is making my system unqualified. I am guessing this issue is related to issue 2 with ports? I was not able to find info on opening the ports on stand alone. It showed for AWS & Google Cloud. 

![QQQ1](https://user-images.githubusercontent.com/85257908/128640593-d40ad985-5fa9-4981-8f80-ebe0a621a14e.png)

2) 

![qqq2](https://user-images.githubusercontent.com/85257908/128640623-f96063d8-0188-45f8-a087-7550b9ce7861.jpeg)

Thank You =)

**Comment by Hugo6991** [comment]
The issues temporarily fixed according user's feedback, so we close the issues report.

<img width="683" alt="圖片" src="https://user-images.githubusercontent.com/48922178/130572868-b4d466c4-44f4-4793-8777-47539a3cf87b.png">
