### ISSUE TITLE
how to check the qlauncher version? and how to update?

### ISSUE THREAD

**Issue by pixyruri** [poseidon-network/qlauncher-linux#4]

**Comment by coderkk** [comment]
You can enter this command: `sudo ./qlauncher.sh check`

You can see qlk_app_version, that is you version number.

**Comment by coderkk** [comment]
For upgrade you need to stop the service first.

If you have registered it to systemd, you need to run `sudo systemctl stop qluancher`

If you run from normal then need to run `sudo  ./qlauncher stop`

wget https://github.com/poseidon-network/qlauncher-linux/releases/latest/download/ql-linux.tar.gz -o app.tar.gz
tar -vxzf app.tar.gz -C ~/qlauncher/

**Comment by coderkk** [comment]
@pixyruri Is it working?

**Comment by pixyruri** [comment]
good
