### ISSUE TITLE
/mnt/qlv2: wrong fs type

### ISSUE THREAD

**Issue by sskerry** [poseidon-network/qlauncher-linux#43]
Hello
I have been running qlauncher since v1 on a 160TB nas (truenas). Up until a few days I have had no issues. I started having issues with rewards so I decided to reinstall qlauncher. Now I am getting a "/mnt/qlv2: wrong fs type" every time I try to install it. I have done everything I can think of to find the problem but since nothing has changed on the storage server, or the ubuntu server running qlauncher I am really not sure where to start. After installing it it shows up with 70gb of storage in the app instead of 100tb. 

[qlauncher][INFO] 2021-12-27T05:32:39Z  Downloading binary https://get.qlauncher.poseidon.network/qlauncher/v3/prod/qlauncher-linux
[qlauncher][INFO] 2021-12-27T05:32:44Z  Installing qlauncher to /opt/qlauncherV3/qlauncher
Please enter the storage path you want to share with Poseidon (press Enter directly to share the current path) : /nfs/qqq
Contribute 146191GB of storage capacity to Poseidon (y/n) ? n
Enter the number of storage capacity you are willing to contribute to Poseidon (<=146191GB) : 100000
INFO[2021-12-27 05:32:53]
INFO[2021-12-27 05:32:53]
INFO[2021-12-27 05:32:53] mount: /mnt/qlv2: wrong fs type, bad option, bad superblock on /dev/loop8, missing codepage or helper program, or other error.
INFO[2021-12-27 05:32:54] Install k3s
INFO[2021-12-27 05:32:55] [INFO]  Using v1.19.5+k3s2 as release
INFO[2021-12-27 05:32:55] [INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.19.5+k3s2/sha256sum-amd64.txt
INFO[2021-12-27 05:32:55] [INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.19.5+k3s2/k3s
INFO[2021-12-27 05:32:57] [INFO]  Verifying binary download
INFO[2021-12-27 05:32:58] [INFO]  Installing k3s to /usr/local/bin/k3s
INFO[2021-12-27 05:32:58] [INFO]  Skipping installation of SELinux RPM
INFO[2021-12-27 05:32:58] [INFO]  Creating /usr/local/bin/kubectl symlink to k3s
INFO[2021-12-27 05:32:58] [INFO]  Creating /usr/local/bin/crictl symlink to k3s
INFO[2021-12-27 05:32:58] [INFO]  Skipping /usr/local/bin/ctr symlink to k3s, command exists in PATH at /usr/bin/ctr
INFO[2021-12-27 05:32:58] [INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
INFO[2021-12-27 05:32:58] [INFO]  Creating uninstall script /usr/local/bin/k3s-agent-uninstall.sh
INFO[2021-12-27 05:32:58] [INFO]  env: Creating environment file /etc/systemd/system/k3s-agent.service.env
INFO[2021-12-27 05:32:58] [INFO]  systemd: Creating service file /etc/systemd/system/k3s-agent.service
INFO[2021-12-27 05:32:58] Create systemd file : /etc/systemd/system/qlauncher.service
INFO[2021-12-27 05:32:58] Created symlink /etc/systemd/system/multi-user.target.wants/qlauncher.service → /etc/systemd/system/qlauncher.service.
Killed

**Comment by sskerry** [comment]
Update, it seems to work fine 15TB or less, anything higher generates the error

**Comment by coderkk** [comment]
Yes. Current it use ext3 format, which the limit is 16TB. https://access.redhat.com/solutions/1532
