### ISSUE TITLE
show error when "tar -vxzf app.tar.gz"

### ISSUE THREAD

**Issue by eric-sandboxsmart** [poseidon-network/qlauncher-linux#6]
when running this commend as following
**tar -vxzf app.tar.gz -C ~/qlauncher/**
it shows =>
**gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now**

please advice 
thx

**Comment by coderkk** [comment]
Can you try command below:-

```
wget https://github.com/poseidon-network/qlauncher-linux/releases/latest/download/ql-linux.tar.gz
tar -vxzf ql-linux.tar.gz -C ~/qlauncher/
```

**Comment by eric-sandboxsmart** [comment]
successed , thx
