### ISSUE TITLE
Ubuntu qlauncher start issue

### ISSUE THREAD

**Issue by chilipc** [poseidon-network/qlauncher-linux#8]
![ubuntu qlauncher start issue](https://user-images.githubusercontent.com/67200344/85206806-14295080-b357-11ea-9b95-1b0db669a327.png)

**Comment by coderkk** [comment]
Please try rename path from arm-x41 to aarch64.

**Comment by chilipc** [comment]
Path is updated with qlauncher started but core does not live. Please advise.
![ubuntu qlauncher start issue 2](https://user-images.githubusercontent.com/67200344/85230275-b6156f80-b421-11ea-8b34-9931b82f9641.png)

**Comment by coderkk** [comment]
Maybe the backend can't support aarch64.

Please try open edge.yaml.template and look for podsandbox-image. Replace $pause to kubeedge/pause-arm64:3.1. Then restart.

**Comment by coderkk** [comment]
Hi @chilipc May I know your qlauncher can run or not?

**Comment by chilipc** [comment]
Hi,

Thanks for support. I'll try to proceed to see if it works & come back to
you.

Does the issue result due to latest Ubuntu 20.04 installed? Is the current
qlauncher version applicable to Ubuntu 18.04 only? If yes maybe Ubuntu
downgrade is a proper solution instead.

coderkk <notifications@github.com> 於 2020年6月23日 週二 下午1:09寫道：

**Comment by coderkk** [comment]
I think because of aarch64. Currently, we have tested in x86_64 and arm, but we not sure about aarch64.

**Comment by chilipc** [comment]
Does it mean I should install Ubuntu 20.04 32-bit instead for arm? To avoid
certain manual changes if aarch64 is not in scope.

coderkk <notifications@github.com> 於 2020年6月23日 週二 下午3:27寫道：

**Comment by coderkk** [comment]
The operating system is ok. aarch64 is the CPU/Processor architecture.

But, let try the above see can solve it or not.

**Comment by coderkk** [comment]
Hi @chilipc, may I know it is work?

**Comment by chilipc** [comment]
Dear support,

The server is located in another location & I need certain time to extract
the content to review. I just explore the content as the screen capture
below.

Do you mean I should replace the highlight $pause to
kubeedge/pause-arm64:3.1 to test? Btw it's a Linux reader in Windows & I'm
looking on the way to update the file content. Please advise if it can be
done in a single step. Thanks.
[image: image.png]


coderkk <notifications@github.com> 於 2020年6月28日 週日 下午9:22寫道：

**Comment by chilipc** [comment]
Dear support,

I updated open edge.yaml.template as stated & restarted the server. The
result is likely the same. Please advise.
[image: image.png]

Best regards,
Chilip

Chilip Chan <chilip.c@gmail.com> 於 2020年6月29日 週一 上午1:48寫道：

**Comment by chilipc** [comment]
Dear support,

Should I continue to test with the device? It's Raspberry Pi 4 for
your info. See if it's applicable to Ubuntu qlauncher in short or long run.

By the way, can you see the screen capture I sent by gmail?

Best regards,
Chilip

Chilip Chan <chilip.c@gmail.com> 於 2020年7月4日 週六 下午9:25寫道：

**Comment by coderkk** [comment]
I see. Currently, we not yet test with Raspberry pi 4. But, we will soon do testing with it. It also part of our plan.

May I know what is your rpi4 spec?

**Comment by chilipc** [comment]
Raspberry Pi 4B
2GB RAM

So I should put the testing on hold & look forward to official update then?

coderkk <notifications@github.com> 於 2020年7月9日 週四 下午1:17寫道：

**Comment by coderkk** [comment]
Yes, we will update when we have released.

**Comment by chilipc** [comment]
I see. Please close the ticket & to be resolved by new release.

coderkk <notifications@github.com> 於 2020年7月9日 週四 下午2:43寫道：
